richardhj.contao_email_token_login.token_login:
    path: /_contao/email_login/{token}
    defaults:
        _scope: frontend
        _token_check: false
        _controller: richardhj.contao_email_token_login.controller.token_login
