services:
    richardhj.contao_email_token_login.controller.token_login:
        class: Richardhj\ContaoEmailTokenLoginBundle\Controller\TokenLogin
        arguments:
            - '@contao.security.frontend_user_provider'
            - '@security.token_storage'
            - '@session'
            - '@database_connection'
            - '@contao.routing.url_generator'
